export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="$HOME/Apps/firefox:$PATH"
export PATH="/usr/local/go/bin:$PATH"
export PATH="/usr/local/texlive/2018/bin/x86_64-linux:$PATH"

eval $(opam config env)
