# Enable profiling
# zmodload zsh/zprof

# Autocompletion w/ once-a-day loading
autoload -Uz compinit
typeset -i updated_at=$(date +'%j' -r ~/.zcompdump 2>/dev/null || stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)
if [ $(date +'%j') != $updated_at ]; then
  compinit -i
else
  compinit -C -i
fi

# Source anitgen for zsh plugin management
ANTIDOTE_DIR="$HOME/.zsh/antidote"
source "$ANTIDOTE_DIR/antidote.zsh"
antidote load "$HOME/.zsh_plugins.txt"

# Prompt configuration
AGKOZAK_LEFT_PROMPT_ONLY=1
AGKOZAK_PROMPT_DIRTRIM=0
AGKOZAK_USER_HOST_DISPLAY=0
AGKOZAK_CUSTOM_SYMBOLS=(
  '⇣⇡' # Diverged
  '⇣' # Behind
  '⇡' # Ahead
  '+' # New file
  'x' # Deleted
  '!' # Modified
  '>' # Renamed
  '?' # Untracked
  '$' # Stashed changes
)
AGKOZAK_PROMPT_CHAR=( ❯ ❯ ❮ )
AGKOZAK_COLORS_PROMPT_CHAR='magenta'


autoload -Uz promptinit && promptinit && prompt agkozak-zsh-prompt

# fzf-tab configuration
zstyle ':completion:*:git-checkout:*' sort false
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':completion:*' menu no   # Match for unambiguous prefixes
zstyle ':completion:*' list-suffixes zstyle ':completion:*' expand prefix suffix 
zstyle ':fzf-tab:*' fzf-flags --color=fg:1,fg+:2 --bind=tab:accept
zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup

# Colorize CLI ouputs
export CLICOLOR=1

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Autocomplete settings
unsetopt menu_complete   # do not autoselect the first completion entry
unsetopt flowcontrol
setopt auto_menu         # show completion menu on successive tab press
setopt complete_in_word
setopt always_to_end
zstyle ':completion:*' menu select # highlight current tab selection


# History settings
export HISTFILE="$HOME/.zsh_history"
export SAVEHIST=100000
export HISTSIZE=100000
setopt hist_ignore_all_dups
setopt hist_reduce_blanks
setopt inc_append_history
setopt share_history

# Extended globbing mode
setopt extended_glob

# Set to vi mode
bindkey -v

# Yank to the system clipboard
function vi-yank-xclip {
    zle vi-yank
   echo "$CUTBUFFER" | pbcopy -i
}

zle -N vi-yank-xclip
bindkey -M vicmd 'y' vi-yank-xclip

# Reduce delay in when switching modes
export KEYTIMEOUT=1

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Git aliases
alias g="git"
alias ga="git add"
alias gc="git commit"
alias gst="git status"
alias gd="git diff"
alias gcb="git checkout -b"
alias gsw="git switch"
alias gp="git push"

# Aliases
alias e="vim"
alias ls="eza"
alias j="z"

# Cargo aliases
alias cb="cargo build"
alias cba="cargo build --all"
alias cr="cargo run"
alias cfa="cargo fmt --all"

# zprof
