#!/usr/bin/env zsh

# Color constants
yellow="\e[33;40m"
red="\e[31;40m"
green="\e[32;40m"
reset="\e[39;49m"

# Get options.
LNOPTS=""
if [ $# -gt 0 ]; then
  if [[ "$1" == "-f" ]]; then
    LNOPTS="-f"
  else
    echo "Unrecognized option: $1"
    cat << EOF
Usage: $me [OPTIONS]

    Options:
    -f    Force 'ln' to create a new link, even if one already exists with the
          same name.
EOF
    exit 1
  fi
fi

if ! hash nvim; then
  echo "nvim not installed...exiting"
  exit 1
fi

wd=`pwd`
LINKDIR=$HOME/.config/nvim
CONFIGS=./config
mkdir -p $LINKDIR/config

# Linking init.vim
echo -n "linking $wd/init.vim -> $LINKDIR/init.vim..."
if [ -e "$LINKDIR/init.vim" ]; then
  echo "${yellow}Exists${reset}"
else
  ln -s $LNOPTS "$wd/init.vim" "$LINKDIR/init.vim"

  if [ $? -eq 0 ]; then
    echo "${green}OK${reset}"
  else
    echo "${red}Failed${reset}"
  fi
fi

# linking configs
for dotfile in `find $CONFIGS -mindepth 1`; do
  echo -n "Linking $wd/$dotfile -> $LINKDIR/$dotfile..."
  if [ -e $LINKDIR/$dotfile ]; then
    echo "${yellow}Exists${reset}"
  else
    ln -s $LNOPTS "$wd/$dotfile" "$LINKDIR/$dotfile" # > /dev/null 2&>1

    if [ $? -eq 0 ]; then
      echo "${green}OK${reset}"
    else
      echo "${red}Failed${reset}"
    fi
  fi
done
